services:
  voice-app:
    image: asia-northeast1-docker.pkg.dev/cyberagent-285/dialogue-demo/dialogue_demo_image:latest
    platform: linux/amd64
    build:
      context: .
      cache_from:
        - asia-northeast1-docker.pkg.dev/cyberagent-285/dialogue-demo/dialogue_demo_image:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8888
    ports:
      - "8080:8080"
    env_file:
      - .env
