services:
  voice-app:
    image: asia-northeast1-docker.pkg.dev/cyberagent-285/dev-aim-voice/voice-app:latest
    platform: linux/amd64
    build:
      context: ./mod/voice_app
      cache_from:
        - asia-northeast1-docker.pkg.dev/cyberagent-285/dev-aim-voice/voice-app:latest
    command: honcho -f Procfile.dev start app --no-prefix --no-colour
    volumes:
      - "./ai-keymaps/cyberagent-285-03dff0795e3a.json:/cyberagent-285-03dff0795e3a.json"
    ports:
      - "8080:8080"
    env_file:
      - ./mod/voice_app/.env
    links:
      - db
  db:
    image: "gcr.io/cloudsql-docker/gce-proxy:1.16"
    platform: "linux/amd64"
    command: [ "./cloud_sql_proxy", "-instances=cyberagent-285:asia-northeast1:aim-dev-master-rdb=tcp:0.0.0.0:3308", "-credential_file=./cyberagent-285-03dff0795e3a.json" ]
    volumes:
      - "./ai-keymaps/cyberagent-285-03dff0795e3a.json:/cyberagent-285-03dff0795e3a.json"
    ports:
      - "3308:3308"
