# src/modules/dialogue/constants/dialogue_state.py

from enum import Enum, IntEnum

class DialogueState(str, Enum):
    """対話の状態を表すEnum"""
    START = "START"
    CONTINUE = "CONTINUE"
    SLOTS_FILLED = "SLOTS_FILLED"
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    CORRECTION = "CORRECTION"
    COMPLETE = "COMPLETE"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"
    INTENT_CHANGED = "INTENT_CHANGED"
    FALLBACK = "FALLBACK"

class Intent(str, Enum):
    """対話の意図を表すEnum"""
    NEW_RESERVATION = "新規予約"
    CONFIRM_RESERVATION = "予約内容の確認"
    CANCEL_RESERVATION = "予約のキャンセル"
    CHANGE_RESERVATION = "予約の変更"
    ASK_ABOUT_STORE = "店舗についての質問"
    CHANGE = "CHANGE"
    YES = "YES"
    NO = "NO"
    OTHER = "OTHER"

GLOBAL_INTENTS = [
    Intent.NEW_RESERVATION,
    Intent.CONFIRM_RESERVATION,
    Intent.CANCEL_RESERVATION,
    Intent.CHANGE_RESERVATION,
    Intent.ASK_ABOUT_STORE,
] 
    
class RoutingResult(str, Enum):
    """意図のルーティング結果を表すEnum"""
    NO_INTENT = "NO_INTENT"
    INVALID_INTENT = "INVALID_INTENT"
    CONTINUE = "CONTINUE"
    CONFIRM = "CONFIRM"
    CHANGE = "CHANGE"
    CANCEL = "CANCEL"
    INTENT_CHANGED = "INTENT_CHANGED"
    INTENT_UNCHANGED = "INTENT_UNCHANGED"
    ESCALATE = "ESCALATE"
    FALLBACK = "FALLBACK"
    YES = "YES"
    NO = "NO"

class Slot(str, Enum):
    """スロットの種類を表すEnum"""
    NAME = "名前"
    DATE = "日付"
    TIME = "時間"
    N_PERSON = "人数"
    

class TTSLabel(str, Enum):
    """音声合成のラベルを表すEnum"""
    # 基本的な応答
    SELECT = "SELECT"
    INITIAL_1 = "INITIAL_1"
    INITIAL_2 = "INITIAL_2"
    FILLER = "FILLER"
    APOLOGIZE = "APOLOGIZE"

    # 初期の質問
    DATE_1 = "DATE_1"
    TIME_1 = "TIME_1"
    N_PERSON_1 = "N_PERSON_1"
    NAME_1 = "NAME_1"
    
    # 修正時の質問
    DATE_2 = "DATE_2"
    TIME_2 = "TIME_2"
    N_PERSON_2 = "N_PERSON_2"
    NAME_2 = "NAME_2"

    # 新規予約関連
    NEW_RESERVATION_INTRO = "NEW_RESERVATION_INTRO"
    NEW_RESERVATION_COMPLETE = "NEW_RESERVATION_COMPLETE"
    NEW_RESERVATION_CANCEL = "NEW_RESERVATION_CANCEL"
    NEW_RESERVATION_CHANGE = "NEW_RESERVATION_CHANGE"
    
    # 予約確認関連
    CONFIRM_RESERVATION_INTRO = "CONFIRM_RESERVATION_INTRO"
    CONFIRM_RESERVATION_COMPLETE = "CONFIRM_RESERVATION_COMPLETE"
    CONFIRM_RESERVATION_NAME = "CONFIRM_NAME"
    CONFIRM_RESERVATION_DATE = "CONFIRM_DATE"
    CONFIRM_RESERVATION_CONFIRM = "CONFIRM_RESERVATION_CONFIRM"
    CONFIRM_RESERVATION_CANCEL = "CONFIRM_RESERVATION_CANCEL"
    
    # 予約キャンセル関連
    CANCEL_RESERVATION_INTRO = "CANCEL_RESERVATION_INTRO"
    CANCEL_RESERVATION_COMPLETE = "CANCEL_RESERVATION_COMPLETE"
    CANCEL_RESERVATION_CONFIRM = "CANCEL_RESERVATION_CONFIRM"
    CANCEL_RESERVATION_CANCEL = "CANCEL_RESERVATION_CANCEL"
    CANCEL_RESERVATION_NAME = "CANCEL_NAME"
    
    # 店舗案内関連
    STORE_INFO_INTRO = "STORE_INFO_INTRO"
    STORE_INFO_COMPLETE = "STORE_INFO_COMPLETE"
    STORE_INFO_NOT_FOUND = "STORE_INFO_NOT_FOUND"
    
    # 共通のフォールバック応答
    FALLBACK_INVALID_INTENT = "FALLBACK_INVALID_INTENT"
    FALLBACK_NO_INTENT = "FALLBACK_NO_INTENT"
    FALLBACK_CONVERSATION_ERROR = "FALLBACK_CONVERSATION_ERROR"
    FALLBACK_DEFAULT = "FALLBACK_DEFAULT"
    
    # 確認関連の定型文
    ASK_OTHER_QUESTIONS = "ASK_OTHER_QUESTIONS"
    THANKS_FOR_QUESTION = "THANKS_FOR_QUESTION"
    
    # 予約変更関連
    CHANGE_RESERVATION_INTRO = "CHANGE_RESERVATION_INTRO"

class VADConfig(int, Enum):
    SAMPLE_RATE = 8000
    VOLUME_THRESHOLD = 1000
    FAST_SPEECH_END_THRESHOLD = 20
    SLOW_SPEECH_END_THRESHOLD = 80
    

class BargeInConfig:
    BARGE_IN_THRESHOLD = 20
    BARGE_IN_UTTERANCE = [
        TTSLabel.DATE_1,
        TTSLabel.TIME_1,
        TTSLabel.N_PERSON_1,
        TTSLabel.NAME_1,
        TTSLabel.DATE_2,
        TTSLabel.TIME_2,
        TTSLabel.N_PERSON_2,
        TTSLabel.NAME_2,
    ]


class TurnTakingStatus(IntEnum):
    END_OF_TURN = 0
    BACKCHANNEL = 1
    CONTINUE = 2